### ISSUE TITLE
Feature update: handle incomplete reads

### ISSUE THREAD

**Issue by Junjun-zhao** [DHancock/Countdown#22]
.NET 6 has introduced a breaking change for handling incomplete reads from DeflateStream. This was discovered in dotnet/runtime#54538.

Please see dotnet/docs#24649 for more details. If you want to make it work for .NET 6, you will need to update https://github.com/DHancock/Countdown/blob/3e86bcc8897e3a5f921cb0cc66421cbf5814a65a/Countdown/Models/WordDictionary.cs#L274-L275

Please refer to below detailed example for the issue:

**App**: Countdown (.NET 5.0 App)
**GitHub Links**: https://github.com/DHancock/Countdown

**Test scenarios**:
Windows 10 RS5 X64 + 5.0.300 PASS
Windows 10 RS5 X64 + 6.0.100-preview.6.21321.10: Fail

**Repro steps:**

1. Publish and launch Countdown.exe. 
2. Click Conundrum tab. 
3. Input “emethyntp” . 
4. Click “Solve” button. 

**Expected Result:**
nymphette item show. 

**Actual Result:**
Can't click the "solve" button after inputting "emethyntp".

**Comment by newDevC** [comment]
can you please check your email : code@davidhancock.net
